
services:
  envoy:
    image: envoyproxy/envoy:v1.22.0
    volumes:
      - ./envoy:/etc/envoy
    networks:
      - rate_limit_network
    expose:
      - "8000"
    ports:
      - "8000:8000"
    depends_on:
      - node

  node:
    build:
      context: node
    networks:
      - rate_limit_network
    expose:
      - "3000"
    ports:
      - "3000:3000"

  registry:
    image: descartesresearch/teastore-registry
    expose:
      - "8080"
    ports:
      - "8083:8080"
    networks:
      - rate_limit_network

  db:
    image: descartesresearch/teastore-db
    expose:
      - "3306"
    ports:
      - "3306:3306"
    networks:
      - rate_limit_network

  persistence:
    image: descartesresearch/teastore-persistence
    expose:
      - "8080"
    ports:
      - "8084:8080"
    environment:
      HOST_NAME: "persistence"
      REGISTRY_HOST: "registry"
      DB_HOST: "db"
      DB_PORT: "3306"
    networks:
      - rate_limit_network

  auth:
    image: descartesresearch/teastore-auth
    expose:
      - "8080"
    ports:
      - "8085:8080"
    environment:
      HOST_NAME: "auth"
      REGISTRY_HOST: "registry"
    networks:
      - rate_limit_network

  image:
    image: descartesresearch/teastore-image
    expose:
      - "8080"
    ports:
      - "8086:8080"
    environment:
      HOST_NAME: "image"
      REGISTRY_HOST: "registry"
    networks:
      - rate_limit_network

  recommender:
    image: descartesresearch/teastore-recommender
    expose:
      - "8080"
    ports:
      - "8087:8080"
    environment:
      HOST_NAME: "recommender"
      REGISTRY_HOST: "registry"
    networks:
      - rate_limit_network

  webui:
    image: descartesresearch/teastore-webui
    expose:
      - "8080"
    ports:
      - "8082:8080"  # Expose on different port since port 8080 is used by Envoy
    environment:
      HOST_NAME: "webui"
      REGISTRY_HOST: "registry"
    networks:
      - rate_limit_network

networks:
  rate_limit_network:
